# Generated by Django 5.2.5 on 2025-08-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClickupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_token", models.CharField(max_length=255)),
                (
                    "clickup_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "clickup_user_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clickup_user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("teams", models.JSONField(blank=True, null=True)),
                (
                    "default_team_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GithubConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_access_token", models.CharField(max_length=255)),
                (
                    "api_base_url",
                    models.CharField(default="https://api.github.com", max_length=255),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "primary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("preferred_author_emails", models.JSONField(blank=True, null=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GithubRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("html_url", models.URLField()),
                (
                    "default_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("private", models.BooleanField(default=False)),
                ("owner_login", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_branches_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GithubBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("head_sha", models.CharField(blank=True, max_length=64, null=True)),
                ("protected", models.BooleanField(default=False)),
                ("last_commits_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="tracker.githubrepo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GithubCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(db_index=True, max_length=64)),
                ("message", models.TextField()),
                ("author_name", models.CharField(max_length=255)),
                ("author_email", models.EmailField(max_length=254)),
                ("date", models.DateTimeField()),
                ("html_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="tracker.githubbranch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "sha"), name="uniq_branch_sha"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="githubbranch",
            constraint=models.UniqueConstraint(
                fields=("repo", "name"), name="uniq_repo_branch_name"
            ),
        ),
    ]
