# Generated by Django 4.2.4 on 2025-08-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubCommitTimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_minutes", models.PositiveIntegerField()),
                (
                    "parsed_from_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_synced_with_clickup", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_log",
                        to="tracker.githubcommit",
                    ),
                ),
            ],
        ),
    ]
