# Generated by Django 5.2.5 on 2025-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_githubcommittimelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubcommittimelog",
            name="task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
