# Generated by Django 5.2.5 on 2025-08-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_githubcommittimelog_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickupTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clickup_id", models.CharField(max_length=100, unique=True)),
                (
                    "user_friendly_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("team_id", models.CharField(blank=True, max_length=100, null=True)),
                ("list_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="githubbranch",
            name="clickup_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="tracker.clickuptask",
            ),
        ),
        migrations.AddField(
            model_name="githubcommittimelog",
            name="clickup_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_logs",
                to="tracker.clickuptask",
            ),
        ),
    ]
